sudo: required

services:
  - docker

language: java

jdk: openjdk8

script: mvn clean install

notifications:
  email:
    recipients:
      - qlack@eurodyn.com
    on_success: change
    on_failure: change